### ISSUE TITLE
Errors: improve UX 

### ISSUE THREAD

**Issue by queil** [queil/rooz#70]
The following cases:
- [x] ~trying to remove a running workspace results in:~ WON'T FIX - see comments
 
   ```
    thread 'main' panicked at src/api/container.rs:111:23:
    Docker responded with status code 500: cannot remove container 15da078e31efd816249cf5f645cf82e619e7dd91da22d7cdf6c38ccd5ddd3f3a as it is running - running or paused containers cannot be removed without force: container state improper
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    ```

    It should gracefully exit suggesting using `--force`

- [x] trying to enter a non-existent container:

    ```
    thread 'main' panicked at src/api/workspace.rs:382:20:
    Container not found
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    ```

    It should gracefully exit with a meaningful message

- [x] trying editing a non-exsistent workspace config:
        It exits without any messages. It should output a meaningful message that the workspace does not exist.

**Comment by queil** [comment]
> trying to remove a running workspace results in
This is not trivial to fix as different backends return different status codes and messages. Hence, rooz will display the message and the code as is, rather than panicking.
